# Netlify 部署配置
[build]
  # 构建命令
  command = "npm install"
  # 发布目录
  publish = "public"
  # 函数目录
  functions = "netlify/functions"

# Functions 运行时配置
[functions]
  # 指定 Node.js 版本
  node_bundler = "esbuild"
  
[build.environment]
  # 指定 Node.js 版本
  NODE_VERSION = "18"

# 重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 环境变量（在 Netlify 控制台中设置）
# NEXUS_API_KEY = "your_nexus_api_key_here"
